### ISSUE TITLE
error after updating to the plugin latest version

### ISSUE THREAD

**Issue by appleimperio** [kuestess/homebridge-platform-insteonlocal#217]
TypeError: Cannot read properties of undefined (reading 'id')
    at /homebridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2150:19
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

It's crashing homebridge

**Comment by kuestess** [comment]
@appleimperio Can you post output of the plugin startup in debug mode?  `homebridge -D`

**Comment by appleimperio** [comment]
@kuestess any idea of how to do this in docker? thanks

**Comment by kuestess** [comment]
@appleimperio Assuming you’re using the homebridge ui, click the three dots at the top right, choose homebridge settings, and then turn on the debug switch.

**Comment by appleimperio** [comment]
```
[5/2/2022, 10:45:10 AM] ---
[5/2/2022, 10:45:14 AM] Loaded plugin: homebridge-platform-insteonlocal@0.4.25
homebridge API version: 2.7
[5/2/2022, 10:45:14 AM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[5/2/2022, 10:45:14 AM] ---
[5/2/2022, 10:45:14 AM] Loaded plugin: homebridge-config-ui-x@4.43.2
[5/2/2022, 10:45:14 AM] Registering platform 'homebridge-config-ui-x.config'
[5/2/2022, 10:45:14 AM] ---
[5/2/2022, 10:45:14 AM] Loading 2 platforms...
[5/2/2022, 10:45:14 AM] [Config] Initializing config platform...
[5/2/2022, 10:45:14 AM] [Config] Running in Service Mode
[5/2/2022, 10:45:14 AM] [HOGAR] Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from /homebridge/config.json
Found 2 platform(s) in config
Creating new insteon.json
No devices in config
[5/2/2022, 10:45:15 AM] [HOGAR] Started connection watcher...
[5/2/2022, 10:45:15 AM] [HOGAR] Found 15 devices in config
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Hallway'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Rod'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Counter'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Kitchen'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Bedroom Light'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Dining'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Exhaust'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Bathtub'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Vanity'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Heat'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'MU Light'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'The Light'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Foyer'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Closet'...
[5/2/2022, 10:45:15 AM] Initializing platform accessory 'Pendant'...
Setup Payload:
X-HM://00247K9QN8IEH
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

(node:15988) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Insteon]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[5/2/2022, 10:45:15 AM] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 6323) is running on port 52994.
[5/2/2022, 10:45:25 AM] TypeError: Cannot read properties of undefined (reading 'id')
    at /homebridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2150:19
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[5/2/2022, 10:45:25 AM] Got SIGTERM, shutting down Homebridge...
[5/2/2022, 10:45:30 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/2/2022, 10:45:35 AM] [HB Supervisor] Restarting Homebridge...
[5/2/2022, 10:45:35 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/2/2022, 10:45:36 AM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 16012
[5/2/2022, 10:45:38 AM] Loaded config.json with 0 accessories and 2 platforms.
[5/2/2022, 10:45:38 AM] Loaded 0 cached accessories from cachedAccessories.
[5/2/2022, 10:45:38 AM] ---
[5/2/2022, 10:45:42 AM] Loaded plugin: homebridge-platform-insteonlocal@0.4.25
homebridge API version: 2.7
[5/2/2022, 10:45:42 AM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[5/2/2022, 10:45:42 AM] ---
[5/2/2022, 10:45:42 AM] Loaded plugin: homebridge-config-ui-x@4.43.2
[5/2/2022, 10:45:42 AM] Registering platform 'homebridge-config-ui-x.config'
[5/2/2022, 10:45:42 AM] ---
[5/2/2022, 10:45:42 AM] Loading 2 platforms...
[5/2/2022, 10:45:42 AM] [Config] Initializing config platform...
[5/2/2022, 10:45:42 AM] [Config] Running in Service Mode
[5/2/2022, 10:45:42 AM] [HOGAR] Initializing InsteonLocal platform...
```

**Comment by kuestess** [comment]
@appleimperio It doesn't look like the plugin is able to connect to your hub.  Are you using the user/pass from the bottom of the hub?  If so, or it was working previously, you might need to restart your hub.

**Comment by kuestess** [comment]
@appleimperio @dhughestrimark I just pushed an update that may address this issue - try updating to the latest release (0.0.26).

**Comment by appleimperio** [comment]
@kuestess thanks for your help first I install the update and the error change then I follow your suggestion and change the username and password from the box and keep getting the new error.

```
Setup Payload:
X-HM://00247K9QN8IEH
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 447-29-725 │     
    └────────────┘     
                       
[5/3/2022, 1:19:01 PM] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 6323) is running on port 52994.
[5/3/2022, 1:19:11 PM] TypeError: self.log is not a function
    at /homebridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2146:9
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[5/3/2022, 1:19:11 PM] Got SIGTERM, shutting down Homebridge...
[5/3/2022, 1:19:16 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/3/2022, 1:19:21 PM] [HB Supervisor] Restarting Homebridge...
[5/3/2022, 1:19:21 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/3/2022, 1:19:21 PM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 3073
[5/3/2022, 1:19:24 PM] Loaded config.json with 0 accessories and 2 platforms.
[5/3/2022, 1:19:24 PM] Loaded 0 cached accessories from cachedAccessories.
[5/3/2022, 1:19:24 PM] ---
[5/3/2022, 1:19:28 PM] Loaded plugin: homebridge-platform-insteonlocal@0.4.26
homebridge API version: 2.7
[5/3/2022, 1:19:28 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[5/3/2022, 1:19:28 PM] ---
[5/3/2022, 1:19:28 PM] Loaded plugin: homebridge-config-ui-x@4.43.2
[5/3/2022, 1:19:28 PM] Registering platform 'homebridge-config-ui-x.config'
[5/3/2022, 1:19:28 PM] ---
[5/3/2022, 1:19:28 PM] Loading 2 platforms...
[5/3/2022, 1:19:28 PM] [Config] Initializing config platform...
[5/3/2022, 1:19:28 PM] [Config] Running in Service Mode
[5/3/2022, 1:19:28 PM] [HOGAR] Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from /homebridge/config.json
Found 2 platform(s) in config
Creating new insteon.json
No devices in config
[5/3/2022, 1:19:28 PM] [HOGAR] Started connection watcher...
[5/3/2022, 1:19:28 PM] [HOGAR] Found 15 devices in config
[5/3/2022, 1:19:28 PM] Initializing platform accessory 'Hallway'...
[5/3/2022, 1:19:28 PM] Initializing platform accessory 'Rod'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Counter'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Kitchen'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Bedroom Light'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Dining'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Exhaust'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Bathtub'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Vanity'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Heat'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Mu Light'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'The Light'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Foyer'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Closet'...
[5/3/2022, 1:19:29 PM] Initializing platform accessory 'Pendant'...
Setup Payload:
X-HM://00247K9QN8IEH
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 447-29-725 │     
    └────────────┘     
                       
[5/3/2022, 1:19:29 PM] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 6323) is running on port 52994.
[5/3/2022, 1:19:39 PM] TypeError: self.log is not a function
    at /homebridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2146:9
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[5/3/2022, 1:19:39 PM] Got SIGTERM, shutting down Homebridge...
[5/3/2022, 1:19:44 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

**Comment by kuestess** [comment]
@appleimperio I'm an idiot - that error is my fault.  Fix is now pushed.

**Comment by appleimperio** [comment]
@kuestess thank you very much for your help.  no more errors I still can't get it to control the lights but I think is because the Insteon servers are down.

**Comment by kuestess** [comment]
@appleimperio You should be able to control your lights as the plugin doesn't rely on the Insteon servers.  Do the devices show up in Home and what do you see in the log if you try to control them?
